###
POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Kaio",
    "turma": "3º Ano",
    "idade": 17
}

###

GET http://localhost:3000/alunos

###

GET http://localhost:3000/alunos/1
