###
POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Kaio",
    "email": "kaiodilli@gmail.com",
    "turma": "3º Ano"
}

###

GET http://localhost:3000/alunos

###

GET http://localhost:3000/alunos/1
